"""Initial migration

Revision ID: d831ca347721
Revises: 
Create Date: 2026-01-15 13:30:38.351010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd831ca347721'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfp_info',
    sa.Column('rfp_id', sa.Integer(), nullable=False),
    sa.Column('rfp_title', sa.String(length=500), nullable=False),
    sa.Column('rfp_raw_text', sa.Text(), nullable=False),
    sa.Column('rfp_structured_json', sa.JSON(), nullable=True),
    sa.Column('rfp_status', sa.String(length=50), nullable=False),
    sa.Column('rfp_created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rfp_id')
    )
    op.create_index(op.f('ix_rfp_info_rfp_id'), 'rfp_info', ['rfp_id'], unique=False)
    op.create_table('vendor_info',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('vendor_email', sa.String(length=255), nullable=False),
    sa.Column('vendor_rating', sa.Float(), nullable=True),
    sa.Column('vendor_created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('vendor_id')
    )
    op.create_index(op.f('ix_vendor_info_vendor_email'), 'vendor_info', ['vendor_email'], unique=True)
    op.create_index(op.f('ix_vendor_info_vendor_id'), 'vendor_info', ['vendor_id'], unique=False)
    op.create_table('vendor_rfp_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_rfp_id', sa.Integer(), nullable=False),
    sa.Column('fk_vendor_id', sa.Integer(), nullable=False),
    sa.Column('email_raw_text', sa.Text(), nullable=False),
    sa.Column('email_parsed_json', sa.JSON(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('delivery_days', sa.Integer(), nullable=True),
    sa.Column('warranty_years', sa.Float(), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('ai_recommended', sa.Boolean(), nullable=False),
    sa.Column('response_created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fk_rfp_id'], ['rfp_info.rfp_id'], ),
    sa.ForeignKeyConstraint(['fk_vendor_id'], ['vendor_info.vendor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fk_rfp_id', 'fk_vendor_id', name='unique_rfp_vendor')
    )
    op.create_index(op.f('ix_vendor_rfp_response_id'), 'vendor_rfp_response', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_rfp_response_id'), table_name='vendor_rfp_response')
    op.drop_table('vendor_rfp_response')
    op.drop_index(op.f('ix_vendor_info_vendor_id'), table_name='vendor_info')
    op.drop_index(op.f('ix_vendor_info_vendor_email'), table_name='vendor_info')
    op.drop_table('vendor_info')
    op.drop_index(op.f('ix_rfp_info_rfp_id'), table_name='rfp_info')
    op.drop_table('rfp_info')
    # ### end Alembic commands ###
